# Generated by Django 5.2.5 on 2025-08-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_home_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(),
        ),
    ]
