# Generated by Django 5.2.5 on 2025-08-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_aboutus_content_alter_home_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='project_logos/'),
        ),
    ]
