# Generated by Django 5.2.5 on 2025-08-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('achievements', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_us_images/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
