# Generated by Django 5.2.5 on 2025-09-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_our_team_delete_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_team', to='projects.project'),
        ),
    ]
