# Generated by Django 5.2.5 on 2025-09-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_our_team_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project'},
        ),
        migrations.RemoveField(
            model_name='our_team',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='team_member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.our_team'),
        ),
    ]
