# Generated by Django 5.2.5 on 2025-09-02 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options_remove_our_team_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='resume',
            field=models.FileField(default=None, upload_to='about_us_resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
