# Generated by Django 5.2.5 on 2025-09-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_our_team_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='expertise',
            field=models.TextField(),
        ),
    ]
