# Generated by Django 5.2.5 on 2025-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_our_team_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='expertise',
            field=models.CharField(max_length=100),
        ),
    ]
