# Generated by Django 5.2.5 on 2025-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_our_team_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='home',
        ),
        migrations.AlterModelOptions(
            name='our_team',
            options={'verbose_name': 'Our_Team', 'verbose_name_plural': 'Our_Team'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='video',
        ),
        migrations.AddField(
            model_name='our_team',
            name='designation',
            field=models.CharField(default='Member', max_length=100),
        ),
        migrations.AddField(
            model_name='our_team',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_team',
            name='previous_work',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='our_team',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='HomeImage',
        ),
    ]
