# Generated by Django 5.2.5 on 2025-09-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_homeimage_home_alter_our_team_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_team',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='our_team',
            name='start_date',
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='projects.our_team')),
            ],
        ),
    ]
