# Generated by Django 5.2.5 on 2025-09-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_our_team_end_date_remove_our_team_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_team',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='our_team',
            name='previous_work',
        ),
    ]
