# Generated by Django 5.2.5 on 2025-09-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_our_team_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='work_experience_logos/'),
        ),
    ]
