# Generated by Django 5.2.5 on 2025-09-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_workexperience_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='previous_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
