# Generated by Django 5.2.5 on 2025-09-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_workexperience_previous_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='previous_work',
        ),
        migrations.AddField(
            model_name='our_team',
            name='previous_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
