# Generated by Django 5.2.5 on 2025-09-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_workexperience_previous_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_team',
            name='previous_work',
        ),
    ]
